### ISSUE TITLE
Remover um "0" a mais no valor total

### ISSUE THREAD

**Issue by vinicius-virtuoso** [reinaldonunes/fuel-calc-js#1]
mais exatamente na linha 38 , você está inserindo 3 casas após a "," (no caso é ponto)... Altere para apenas 2 casas .

Seu codigo:
`rsdesloc.textContent = "R$ " + totalPrice.toFixed(3);`

Exemplo:
`rsdesloc.textContent = "R$ " + totalPrice.toFixed(2);`

**Comment by reinaldonunes** [comment]
Valeu pela sugestão, já removi :D
